version: '3'    #docker-compose 支持的版本号，目前是3
services:       #定义服务开始
  mynuget:      #容器名
    image: sunside/simple-nuget-server  #镜像
    ports:                          #端口映射
      - 9001:80                     
    volumes:                        #卷挂载
      - /home/nuget/data:/var/www/db
      - /home/nuget/packages:/var/www/packagefiles
    environment:                #环境变量
      - NUGET_API_KEY=123456